### PR TITLE
Add Installation Instructions to README.md

### PR DESCRIPTION
**Pull request by mikemhenry**
I would be happy to add more, not sure if we want to mention using a virtual environment, or using `pipx` to install it. Personally for tools like this, I like to use `pipx` so I can use it system wide and not worry about which conda env or python virtual env I have activated.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Ah I see you have this documented quite well here: https://vsoch.github.io/action-updater/getting_started/installation.html#installation

But I think that it is worth having some of this in the README, unless you want to try and get people to read the docs.

**Comment by vsoch** [comment]
Hey there! We have this instruction in the Installation section of our user guide: https://vsoch.github.io/action-updater/getting_started/installation.html#getting-started-installation.

**Comment by mikemhenry** [comment]
I'm updating the PR with a better code snippet of the docs.

**Comment by vsoch** [comment]
Ah gotcha, sure we could have a quick how to install there! I think you might want to double check the name of what you are installing though! See the docs I linked.

**Comment by mikemhenry** [comment]
Ha! That was a copy and paste bug, I posted in another issue about `action-lint` (I installed the right tool IRL)

**Comment by mikemhenry** [comment]
I also fixed a mistake in the link to the package on pypi in the docs

**Comment by mikemhenry** [comment]
@vsoch ready for review!

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Thank you @mikemhenry ! :partying_face:

**Pull request merged**
